# No newline before prompt
add_newline = false

# Do not break prompt into two lines
[line_break]
disabled = true

[character]
success_symbol = "[ï”](bold green)"
error_symbol = "[ï”](bold red)"
vicmd_symbol = "[ï“](bold yellow)"

[directory]
style = "bold blue"
read_only = " ğŸ”’"
truncation_length = 2
fish_style_pwd_dir_length = 1

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold red"

# Disable modules
[cmake]
disabled = true

[python]
disabled = true

[lua]
disabled = true

[nodejs]
disabled = true

[rust]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true
